site:
  about:
    siteName: 'Pebble Templates'
    subtitle: 'A lightweight but rock solid Java templating engine.'

theme:
  primaryColor: '#72A6D0'
  menu:
    # About section
    - type: 'separator'
      title: 'About'
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'page'
      itemId: 'Twig Compatibility'
    - type: 'page'
      itemId: 'Contributing'
    - type: 'link'
      title: 'Offline Documentation (PDF)'
      url: '#{$0|baseUrl}/wiki/book.pdf'
    # Integration section
    #     Spring Integration section
    - type: 'separator'
      title: 'Integration'
    - type: 'page'
      itemId: 'Spring Boot Integration'
    - type: 'link'
      title: 'Pebble Spring Example'
      url: 'https://github.com/PebbleTemplates/pebble-example-spring'
    - type: 'link'
      title: 'Spring petclinic example'
      url: 'https://github.com/PebbleTemplates/spring-petclinic'
    #     Ktor Integration section
    - type: 'link'
      title: 'Ktor Integration'
      url: 'https://ktor.io/servers/features/templates/pebble.html'
    #     Vert.x Integration section
    - type: 'link'
      title: 'Vert.x Integration'
      url: 'https://vertx.io/preview/docs/vertx-web/java/#_pebble_template_engine'

    # Wiki section
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'

    # API Docs section
    - type: 'separator'
      title: 'API Docs'
    - type: 'page'
      title: 'Javadocs'
      itemId: 'com.mitchellbosecke.pebble'
  extraCss:
    - 'assets/css/pygments.scss'
    - 'assets/css/orchidJavadoc.scss'
    - 'assets/css/github-fork-ribbon.css'

services:
  publications:
    stages:
      - type: githubPages
        branch: gh-pages
        publishType: CleanBranch
        username: PebbleTemplates
        repo: pebble
      - type: githubReleases
        repo: 'PebbleTemplates/pebble'

allPages:
  components:
    - type: 'pageContent'
    - type: 'prism'
      languages:
        - 'java'
        - 'twig'
        - 'markup'

wiki:
  defaultConfig:
    includeIndexInPageTitle: false
    createPdf: true

javadoc:
  sourceDirs:
    - '../../../../pebble/src/main/java'
  pages:
    menu:
      - type: 'javadocPackages'
      - type: 'javadocClasses'
